GET_BY_TITLE_OPTION = "1"
GET_BY_GENRE_OPTION = "2"
GET_BY_YEAR_OPTION = "3"
GET_TOP_10_SEARCH_QUERIES = "4"
EXIT_OPTION = "0"

FILM_COUNT_PER_PAGE = 10

QUERY_TYPE_TITLE = 1
QUERY_TYPE_GENRE = 2
QUERY_TYPE_YEAR = 3